## Text Vectorization in Machine Learning

Text vectorization is the process of converting textual data into numerical representations so that machine learning algorithms can understand and work with them. It is a critical step in NLP pipelines.

### Common Techniques

- **Bag of Words (BoW)**  
  Represents text by word count. Ignores word order but preserves frequency.

- **TF-IDF (Term Frequency - Inverse Document Frequency)**  
  Balances word frequency with how unique the word is across documents.

- **Word Embeddings (e.g., Word2Vec, GloVe)**  
  Captures semantic meaning of words in dense vectors.

- **Contextual Embeddings (e.g., BERT)**  
  Uses deep learning to understand context.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Sample corpus
corpus = [
    "Machine learning is interesting",
    "Natural language processing with machine learning",
    "Text vectorization converts words to numbers"
]

# Bag of Words - Count Vectorization
bow_vectorizer = CountVectorizer()
bow_matrix = bow_vectorizer.fit_transform(corpus)
print("Bag of Words Matrix:\n", bow_matrix.toarray())
print("Vocabulary:\n", bow_vectorizer.vocabulary_)

# TF-IDF - Term Frequency-Inverse Document Frequency
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
print("\nTF-IDF Matrix:\n", tfidf_matrix.toarray())
print("Vocabulary:\n", tfidf_vectorizer.vocabulary_)

Bag of Words Matrix:
 [[0 1 1 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 1 0 0 0 1 0]
 [1 0 0 0 0 0 0 1 0 1 1 1 0 1]]
Vocabulary:
 {'machine': 5, 'learning': 4, 'is': 2, 'interesting': 1, 'natural': 6, 'language': 3, 'processing': 8, 'with': 12, 'text': 9, 'vectorization': 11, 'converts': 0, 'words': 13, 'to': 10, 'numbers': 7}

TF-IDF Matrix:
 [[0.         0.5628291  0.5628291  0.         0.42804604 0.42804604
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.44036207 0.3349067  0.3349067
  0.44036207 0.         0.44036207 0.         0.         0.
  0.44036207 0.        ]
 [0.40824829 0.         0.         0.         0.         0.
  0.         0.40824829 0.         0.40824829 0.40824829 0.40824829
  0.         0.40824829]]
Vocabulary:
 {'machine': 5, 'learning': 4, 'is': 2, 'interesting': 1, 'natural': 6, 'language': 3, 'processing': 8, 'with': 12, 'text': 9, 'vectorization': 11, 'converts': 0, 'words': 13, 'to': 10

## Word Embeddings and Contextual Embeddings

### Word Embeddings with Word2Vec

In [ ]:
%pip install gensim

In [2]:
from gensim.models import Word2Vec

# Sample corpus
sentences = [
    ["machine", "learning", "is", "fun"],
    ["natural", "language", "processing"],
    ["word", "embedding", "captures", "meaning"]
]

# Train Word2Vec model
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# Get vector for a word
vector = model.wv["machine"]
print("Vector for 'machine':\n", vector)

# Find similar words
similar = model.wv.most_similar("learning")
print("Words similar to 'learning':\n", similar)

Vector for 'machine':
 [ 7.0887972e-03 -1.5679300e-03  7.9474989e-03 -9.4886590e-03
 -8.0294991e-03 -6.6403709e-03 -4.0034545e-03  4.9892161e-03
 -3.8135587e-03 -8.3199050e-03  8.4117772e-03 -3.7470020e-03
  8.6086961e-03 -4.8957514e-03  3.9185942e-03  4.9220170e-03
  2.3926091e-03 -2.8188038e-03  2.8491246e-03 -8.2562361e-03
 -2.7655398e-03 -2.5911583e-03  7.2490061e-03 -3.4634031e-03
 -6.5997029e-03  4.3404270e-03 -4.7448516e-04 -3.5975564e-03
  6.8824720e-03  3.8723124e-03 -3.9002013e-03  7.7188847e-04
  9.1435025e-03  7.7546560e-03  6.3618720e-03  4.6673026e-03
  2.3844899e-03 -1.8416261e-03 -6.3712932e-03 -3.0181051e-04
 -1.5653884e-03 -5.7228567e-04 -6.2628710e-03  7.4340473e-03
 -6.5914928e-03 -7.2392775e-03 -2.7571463e-03 -1.5154004e-03
 -7.6357173e-03  6.9824100e-04 -5.3261113e-03 -1.2755442e-03
 -7.3651113e-03  1.9605684e-03  3.2731986e-03 -2.3138524e-05
 -5.4483581e-03 -1.7260861e-03  7.0849168e-03  3.7362587e-03
 -8.8810492e-03 -3.4135508e-03  2.3541022e-03  2.1380198e-03
 

### Contextual Embeddings with BERT

In [ ]:
%pip install transformers

In [ ]:
from transformers import BertTokenizer, BertModel
import torch

# Load BERT base model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

In [ ]:
# Input sentence
sentence = "Machine learning is powerful"

# Tokenize input
inputs = tokenizer(sentence, return_tensors="pt") # pt for PyTorch

# Get BERT embeddings
with torch.no_grad():
    outputs = model(**inputs)

# Extract the last hidden state (token-level embeddings)
last_hidden_states = outputs.last_hidden_state
print("Shape of token embeddings:", last_hidden_states.shape)  # (batch_size, seq_len, hidden_dim)

# Get sentence embedding (e.g., mean pooling)
sentence_embedding = last_hidden_states.mean(dim=1)
print("Sentence embedding:\n", sentence_embedding)

Shape of token embeddings: torch.Size([1, 6, 768])
Sentence embedding:
 tensor([[-1.2809e-01, -6.8842e-02, -1.1865e-01,  2.7254e-01,  2.4111e-02,
         -5.0896e-01,  8.0104e-02,  3.0755e-01, -3.8481e-02, -6.0748e-01,
          2.2769e-01, -1.0920e-01, -3.8577e-01,  8.2723e-02, -4.2054e-01,
          1.0584e-02, -3.2371e-02,  1.1315e-01, -2.7826e-01,  1.2768e-01,
         -1.3003e-01,  2.6053e-01, -2.5450e-01,  5.1580e-01,  1.8135e-01,
         -9.9231e-02, -1.7679e-01,  3.5310e-02, -2.4492e-02, -1.6839e-01,
          5.9712e-02,  2.0253e-01, -9.4168e-02,  1.9292e-02, -1.7289e-02,
         -1.5319e-01,  2.3021e-02,  1.9618e-03, -4.4608e-01,  5.9093e-03,
         -2.5396e-02, -4.5986e-02,  2.6158e-02,  3.9706e-01, -1.8318e-01,
         -3.1276e-01, -4.1194e-01,  1.5050e-01,  4.1311e-01, -2.8676e-01,
         -6.8411e-01, -6.3925e-02,  1.5735e-01,  3.9845e-01,  1.3395e-01,
          4.9792e-01,  9.2744e-02,  8.6000e-02,  1.2030e-01, -2.8434e-01,
          1.6401e-01,  4.9790e-02,  8.59

In [4]:
import torch.nn.functional as F

model.eval()  # Set the model to evaluation mode

# Two example sentences
sent1 = "Machine learning is powerful"
sent2 = "Artificial intelligence is strong"

def get_sentence_embedding(sentence):
    # Tokenize input sentence
    inputs = tokenizer(sentence, return_tensors="pt")
    # Get model output without gradient calculation
    with torch.no_grad():
        outputs = model(**inputs)
    # Extract last hidden states (token embeddings)
    last_hidden = outputs.last_hidden_state
    # Return mean pooled sentence embedding
    return last_hidden.mean(dim=1)

# Get sentence embeddings
emb1 = get_sentence_embedding(sent1)
emb2 = get_sentence_embedding(sent2)

# Calculate cosine similarity between embeddings
similarity = F.cosine_similarity(emb1, emb2)

print(f"Cosine Similarity: {similarity.item():.4f}")


Cosine Similarity: 0.8927


## When to Use What?

| Method         | Use Case                                | Pros                          | Cons                        |
|----------------|------------------------------------------|-------------------------------|-----------------------------|
| BoW            | Simple models, small datasets            | Easy to implement             | Sparse, ignores context     |
| TF-IDF         | Baseline text classification             | Weighs rare terms             | Still sparse, no semantics  |
| Word2Vec/GloVe | Semantic similarity, word-level tasks     | Dense, captures meaning       | Needs pretraining/loading   |
| BERT/ELMo      | Context-sensitive tasks (e.g., QA, NER)   | State-of-the-art performance  | Heavy computation required  |


## Notes

- Always clean and normalise text before vectorizing.
- Consider dimensionality reduction (e.g., PCA, TruncatedSVD) if feature size is too large.
- For deep learning models, use embeddings instead of BoW/TF-IDF.